In [1]:
import pandas as pd
import numpy as np

In [ ]:
stats_file = pd.read_csv('download_stats.csv')

/tmp/ipykernel_109733/2783751097.py:1: DtypeWarning: Columns (0: checksum_ok) have mixed types. Specify dtype option on import or set low_memory=False.
  stats_file = pd.read_csv('download_stats.csv')

In [ ]:
stats_file.tail()

,recid,file,bytes,start,end,duration_s,rate_Bps,success,error,expected_size,expected_checksum,computed_checksum_numeric,checksum_ok,attempts
486195,89773,../../data/89773/hzha03pyth6156_hzqq_206.5_115...,46924800.0,1.776176e+09,1.776176e+09,2.264486,2.072205e+07,True,NaN,46924800.0,adler32:908490ad,2.424607e+09,True,1.0
486196,89773,../../data/89773/hzha03pyth6156_hzqq_206.5_115...,47170560.0,1.776176e+09,1.776176e+09,1.915933,2.462015e+07,True,NaN,47170560.0,adler32:b20d0575,2.987198e+09,True,1.0
486197,89773,../../data/89773/hzha03pyth6156_hzqq_206.5_115...,47278080.0,1.776176e+09,1.776176e+09,2.071563,2.282242e+07,True,NaN,47278080.0,adler32:7b5d40ed,2.069709e+09,True,1.0
486198,89773,../../data/89773/hzha03pyth6156_hzqq_206.5_115...,47201280.0,1.776176e+09,1.776176e+09,3.497013,1.349760e+07,True,NaN,47201280.0,adler32:f9b54223,4.189406e+09,True,1.0
486199,89773,../../data/89773/hzha03pyth6156_hzqq_206.5_115...,46909440.0,1.776176e+09,1.776176e+09,2.873268,1.632616e+07,True,NaN,46909440.0,adler32:c7a9185f,3.349748e+09,True,1.0

In [4]:
stats_file['start_date'] = pd.to_datetime(stats_file['start'], unit = 's')
stats_file['start_date'] = stats_file['start_date'].dt.floor('D')  #

In [5]:
stats_file['start_date'].unique()
stats_file.groupby('start_date').count()

,recid,file,bytes,start,end,duration_s,rate_Bps,success,error,expected_size,expected_checksum,computed_checksum_numeric,checksum_ok,attempts
start_date,,,,,,,,,,,,,,
2025-12-03,4882,4882,4882,4882,4882,4882,4882,4882,0,4882,4882,4882,4882,0
2025-12-04,37860,37860,37860,37860,37860,37860,37860,37860,0,37859,37859,37859,37860,37860
2025-12-05,45526,45526,45526,45526,45526,45526,45526,45526,0,45526,45526,45486,45486,45526
2025-12-08,7082,7082,7082,7082,7082,7082,7082,7082,0,7082,7082,7081,7081,7082
2025-12-09,111102,111102,111100,111102,111102,111100,111100,111102,0,111102,111102,111051,111053,111102
2025-12-10,38757,38757,38757,38757,38757,38757,38757,38757,0,38757,38757,38757,38757,38757
2025-12-12,55137,55137,55133,55137,55137,55133,55133,55137,0,55136,55136,55132,55137,55137
2025-12-13,11826,11826,11826,11826,11826,11826,11826,11826,0,11824,11824,11824,11826,11826
2025-12-15,863,863,861,863,863,861,861,863,0,863,863,861,863,863
2025-12-17,28,28,26,28,28,26,26,28,0,28,28,26,28,28
2025-12-18,26628,26628,26628,26628,26628,26628,26628,26628,0,26627,26627,26619,26620,26628
2025-12-19,68931,68931,68931,68931,68931,68931,68931,68931,0,68931,68931,68931,68931,68931
2026-04-14,19250,19250,19250,19250,19250,19250,19250,19250,0,19250,19250,19250,19250,19250

##Fill in the date of the run to be kept:

In [ ]:
stats_file = stats_file[stats_file['start_date'] == '2026-04-14']

In [7]:
stats_file.groupby('start_date').count()

,recid,file,bytes,start,end,duration_s,rate_Bps,success,error,expected_size,expected_checksum,computed_checksum_numeric,checksum_ok,attempts
start_date,,,,,,,,,,,,,,
2026-04-14,19250,19250,19250,19250,19250,19250,19250,19250,0,19250,19250,19250,19250,19250

In [12]:
stats_file.drop(columns = ['start_date'], inplace = True)
stats_file.head()

,recid,file,bytes,start,end,duration_s,rate_Bps,success,error,expected_size,expected_checksum,computed_checksum_numeric,checksum_ok,attempts
466931,89642,../../data/89642/hzha03pyth6156_hinvqq_208_120...,20874240.0,1.776169e+09,1.776169e+09,0.842520,2.477596e+07,True,NaN,20874240.0,adler32:7160b272,1.902163e+09,True,1.0
466932,89642,../../data/89642/hzha03pyth6156_hinvqq_208_120...,20659200.0,1.776169e+09,1.776169e+09,0.679091,3.042186e+07,True,NaN,20659200.0,adler32:31bd25f5,8.344796e+08,True,1.0
466933,89912,../../data/89912/hzha03pyth6156_hinvmu_208_110...,3594240.0,1.776169e+09,1.776169e+09,0.901382,3.987478e+06,True,NaN,3594240.0,adler32:95732087,2.507350e+09,True,1.0
466934,89642,../../data/89642/hzha03pyth6156_hinvqq_208_120...,20828160.0,1.776169e+09,1.776169e+09,0.893895,2.330045e+07,True,NaN,20828160.0,adler32:d351cbc2,3.545353e+09,True,1.0
466935,89642,../../data/89642/hzha03pyth6156_hinvqq_208_120...,20474880.0,1.776169e+09,1.776169e+09,0.689021,2.971590e+07,True,NaN,20474880.0,adler32:1c914d4e,4.792846e+08,True,1.0

In [13]:
stats_file.to_csv('download_stats.csv', index=False)